name: CI Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    UnitTest:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install --frozen-lockfile
            - name: Build
              run: yarn run build
