name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          cache: 'npm'
      - name: cd into frontend
        run: cd frontend
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: yarn run test
      - name: Build
        run: yarn run build
